# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Result.create([
  { :racerName => "Johnson, Rob", :bib => 15, :country => "GBR", :divisionRank => 21, :overallRank => 22, :created_at => "2012-08-12 01:23:53", :updated_at => "2012-08-12 01:23:53", :totalTime => "2000-01-01 09:03:57", :swimTime => "2000-01-01 00:52:59", :bikeTime => "2000-01-01 04:53:48", :runTime => "2000-01-01 03:11:55" },
  { :racerName => "Siddall, John", :bib => 276, :country => "USA", :divisionRank => 142, :overallRank => 1207, :created_at => "2012-08-12 02:12:40", :updated_at => "2012-08-12 02:12:40", :totalTime => "2000-01-01 12:53:48", :swimTime => "2000-01-01 01:23:08", :bikeTime => "2000-01-01 06:35:41", :runTime => "2000-01-01 04:37:41" },
  { :racerName => "Sørensen-markovic, Aleksandar", :bib => 20, :country => "DNK", :divisionRank => 20, :overallRank => 21, :created_at => "2012-08-12 02:13:50", :updated_at => "2012-08-12 02:13:50", :totalTime => "2000-01-01 09:02:54", :swimTime => "2000-01-01 00:52:38", :bikeTime => "2000-01-01 04:57:04", :runTime => "2000-01-01 03:08:43" },
  { :racerName => "Aas, Ted", :bib => 49, :country => "SWE", :divisionRank => 23, :overallRank => 24, :created_at => "2012-08-12 02:14:16", :updated_at => "2012-08-12 02:14:16", :totalTime => "2000-01-01 09:08:00", :swimTime => "2000-01-01 00:52:33", :bikeTime => "2000-01-01 04:49:15", :runTime => "2000-01-01 03:21:49" },
  { :racerName => "Orrach, George", :bib => 1069, :country => "USA", :divisionRank => 221, :overallRank => 1050, :created_at => "2012-08-12 02:17:05", :updated_at => "2012-08-12 02:17:05", :totalTime => "2000-01-01 12:32:25", :swimTime => "2000-01-01 01:16:56", :bikeTime => "2000-01-01 05:38:59", :runTime => "2000-01-01 05:21:53" }
], :without_protection => true )


