# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Result.create([
  { :racerName => "Sinatra, Dean", :bib => 884, :country => "USA", :divisionRank => 84, :overallRank => 419, :created_at => "2012-08-10 01:16:45", :updated_at => "2012-08-10 04:15:46", :totalTime => "2000-01-01 10:58:14", :swimTime => "2000-01-01 01:16:00", :bikeTime => "2000-01-01 01:16:00", :runTime => "2000-01-01 01:16:00" },
  { :racerName => "Botelho, Raymond", :bib => 62, :country => "USA", :divisionRank => 0, :overallRank => 0, :created_at => "2012-08-10 01:16:59", :updated_at => "2012-08-10 01:16:59", :totalTime => "2000-01-01 00:00:00", :swimTime => "2000-01-01 01:16:00", :bikeTime => "2000-01-01 01:16:00", :runTime => "2000-01-01 01:16:00" },
  { :racerName => "Twiss, John", :bib => 1051, :country => "USA", :divisionRank => 375, :overallRank => 1958, :created_at => "2012-08-10 01:20:32", :updated_at => "2012-08-10 01:20:32", :totalTime => "2000-01-01 15:49:14", :swimTime => "2000-01-01 01:20:00", :bikeTime => "2000-01-01 01:20:00", :runTime => "2000-01-01 01:20:00" },
  { :racerName => "Simpson, Michael", :bib => 59, :country => "CAN", :divisionRank => 51, :overallRank => 2087, :created_at => "2012-08-10 01:29:23", :updated_at => "2012-08-10 01:29:23", :totalTime => "2000-01-01 00:00:00", :swimTime => "2000-01-01 01:28:00", :bikeTime => "2000-01-01 01:28:00", :runTime => "2000-01-01 01:28:00" },
  { :racerName => "Siddall, John", :bib => 276, :country => "USA", :divisionRank => 142, :overallRank => 1207, :created_at => "2012-08-10 01:16:20", :updated_at => "2012-08-10 01:16:20", :totalTime => "2000-01-01 12:53:48", :swimTime => "2000-01-01 01:15:00", :bikeTime => "2000-01-01 01:15:00", :runTime => "2000-01-01 01:15:00" },
  { :racerName => "Botelho, Raymond", :bib => 62, :country => "USA", :divisionRank => 0, :overallRank => 0, :created_at => "2012-08-10 01:16:59", :updated_at => "2012-08-10 01:16:59", :totalTime => "2000-01-01 00:00:00", :swimTime => "2000-01-01 01:16:00", :bikeTime => "2000-01-01 01:16:00", :runTime => "2000-01-01 01:16:00" },
  { :racerName => "Teague, Chris", :bib => 339, :country => "USA", :divisionRank => 131, :overallRank => 1022, :created_at => "2012-08-10 04:48:19", :updated_at => "2012-08-10 04:48:19", :totalTime => "2000-01-01 12:29:11", :swimTime => "2000-01-01 04:47:00", :bikeTime => "2000-01-01 04:47:00", :runTime => "2000-01-01 04:47:00" },
  { :racerName => "Hellinga, Paul", :bib => 198, :country => "USA", :divisionRank => 79, :overallRank => 1569, :created_at => "2012-08-10 04:56:15", :updated_at => "2012-08-10 04:56:15", :totalTime => "2000-01-01 13:55:39", :swimTime => "2000-01-01 04:56:00", :bikeTime => "2000-01-01 04:56:00", :runTime => "2000-01-01 04:56:00" }
], :without_protection => true )


